/**
 * Converts the Open Peeps drawings into plain data this app can render.
 *
 * `react-peeps` (MIT code, CC0 art) ships the drawings as React components. We
 * render each one once, with sentinel colors in place of its line and fill
 * color, and write the resulting paths into `src/lib/art/generated`. Nothing is
 * added, removed or reshaped (ADR 0005), and the app itself never touches React.
 *
 * Run with `bun run art`. The generated files are committed, so a checkout
 * needs no network and no React to build.
 */
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import React from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { Accessories } from "react-peeps/lib/peeps/accessories/z_options";
import { Face } from "react-peeps/lib/peeps/face/z_options";
import { Hair } from "react-peeps/lib/peeps/hair/z_options";
import { BustPose } from "react-peeps/lib/peeps/pose/bust/z_options";
import type { ArtPath, ArtPiece } from "../src/lib/art/types.ts";

const LINE = "__LINE__";
const FILL = "__FILL__";

const outputDirectory = path.join(
  import.meta.dirname,
  "..",
  "src",
  "lib",
  "art",
  "generated",
);

/** Reads the attributes of one SVG tag, which React writes as `name="value"`. */
function attributes(tag: string): Record<string, string> {
  const found: Record<string, string> = {};
  for (const [, name, value] of tag.matchAll(/([a-zA-Z-]+)="([^"]*)"/g))
    found[name] = value;
  return found;
}

function convert(name: string, markup: string): ArtPiece {
  // `None` is a real Open Peeps option that draws nothing at all.
  if (markup === "") return { paths: [] };

  const group = markup.match(/^<g(?<attributes>[^>]*)>/);
  if (!group)
    throw new Error(`${name}: the drawing does not start with a group`);
  if (markup.slice(1).includes("<g"))
    throw new Error(`${name}: nested groups are not supported`);

  const paths: ArtPath[] = [];
  for (const [tag] of markup.matchAll(/<path\b[^>]*>/g)) {
    const found = attributes(tag);
    if (!found.d) throw new Error(`${name}: a path has no outline`);
    const fill =
      found.fill === LINE ? "line" : found.fill === FILL ? "fill" : found.fill;
    if (!fill) throw new Error(`${name}: a path has no fill`);
    paths.push({
      d: found.d,
      ...(found.transform ? { transform: found.transform } : {}),
      fill,
      ...(found["fill-rule"] ? { fillRule: found["fill-rule"] } : {}),
    });
  }
  if (paths.length === 0) throw new Error(`${name}: the drawing has no paths`);

  const transform = attributes(group.groups!.attributes).transform;
  return { ...(transform ? { transform } : {}), paths };
}

async function write(
  file: string,
  exportName: string,
  pieces: Record<string, unknown>,
) {
  const entries = Object.entries(pieces).map(([name, piece]) => {
    const markup = renderToStaticMarkup(
      React.createElement(
        piece as React.FC<{ strokeColor: string; backgroundColor: string }>,
        {
          strokeColor: LINE,
          backgroundColor: FILL,
        },
      ),
    );
    return [name, convert(name, markup)] as const;
  });

  const body = entries
    .map(([name, piece]) => `  ${name}: ${JSON.stringify(piece)},`)
    .join("\n");
  const source = [
    "// Generated by scripts/generate-art.ts from the Open Peeps drawings in",
    "// react-peeps (MIT code, CC0 art). Do not edit by hand: run `bun run art`.",
    "import type { ArtPiece } from '../types';",
    "",
    `export const ${exportName}: Record<string, ArtPiece> = {`,
    body,
    "};",
    "",
  ].join("\n");

  await writeFile(path.join(outputDirectory, file), source);
  console.log(
    `${file}: ${entries.length} pieces, ${entries.reduce((total, [, piece]) => total + piece.paths.length, 0)} paths`,
  );
}

await mkdir(outputDirectory, { recursive: true });
await write("hair.ts", "hairArt", Hair);
await write("faces.ts", "faceArt", Face);
await write("accessories.ts", "accessoryArt", Accessories);
await write("poses.ts", "poseArt", BustPose);
