/**
 * Works out how tightly a Cutout can crop around the drawings.
 *
 * Every head-only Cutout has to use one box, or Students' faces would come out
 * at different sizes on the same chart. So we put every hairstyle, every
 * Expression and every piece of eyewear into one SVG, ask the browser for the
 * outline around all of it, and add a small margin. The bust box does the same
 * with every Pose. The numbers are written into
 * `src/lib/art/generated/framing.ts` and committed.
 *
 * Run with `bun run framing` after adding parts to the catalog.
 */
import { writeFile } from "node:fs/promises";
import path from "node:path";
import { chromium } from "@playwright/test";
import {
  clothingColors,
  expressions,
  eyewear,
  hairColors,
  hairstyles,
  poses,
  skinTones,
} from "../src/lib/catalog.ts";
import { defaultAvatar } from "../src/lib/avatar.ts";
import { figureGroups, type FigureGroup } from "../src/lib/render.ts";

const MARGIN = 24;

function markup(groups: FigureGroup[]): string {
  return groups
    .map(
      (group) =>
        `<g${group.transform ? ` transform="${group.transform}"` : ""}>` +
        group.paths
          .map(
            (drawn) =>
              `<path d="${drawn.d}"${drawn.transform ? ` transform="${drawn.transform}"` : ""} fill="${drawn.fill}"${drawn.fillRule ? ` fill-rule="${drawn.fillRule}"` : ""} stroke="none"/>`,
          )
          .join("") +
        "</g>",
    )
    .join("");
}

/** Every combination that could stick out of the box, all drawn at once. */
function everything(framing: "head" | "bust"): string {
  const avatar = defaultAvatar();
  const drawings: string[] = [];
  const each = (count: number, build: (index: number) => void) => {
    for (let index = 0; index < count; index += 1) build(index);
  };

  each(hairstyles.stored.length, (hairstyle) =>
    drawings.push(
      markup(
        figureGroups({ avatar: { ...avatar, hairstyle }, framing, pose: 0 }),
      ),
    ),
  );
  each(expressions.stored.length, (expression) =>
    drawings.push(
      markup(
        figureGroups({ avatar: { ...avatar, expression }, framing, pose: 0 }),
      ),
    ),
  );
  each(eyewear.stored.length, (piece) =>
    drawings.push(
      markup(
        figureGroups({
          avatar: { ...avatar, eyewear: piece },
          framing,
          pose: 0,
        }),
      ),
    ),
  );
  if (framing === "bust") {
    each(poses.stored.length, (pose) =>
      drawings.push(markup(figureGroups({ avatar, framing, pose }))),
    );
  }
  return drawings.join("");
}

async function measure(framing: "head" | "bust") {
  const browser = await chromium.launch();
  try {
    const page = await browser.newPage();
    await page.setContent(
      `<svg id="all" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 2000 2000" width="2000" height="2000">${everything(framing)}</svg>`,
    );
    const box = await page.evaluate(() => {
      const svg = document.getElementById(
        "all",
      ) as unknown as SVGGraphicsElement;
      const { x, y, width, height } = svg.getBBox();
      return { x, y, width, height };
    });
    return {
      x: Math.floor(box.x) - MARGIN,
      y: Math.floor(box.y) - MARGIN,
      width: Math.ceil(box.width) + MARGIN * 2,
      height: Math.ceil(box.height) + MARGIN * 2,
    };
  } finally {
    await browser.close();
  }
}

// Checks nothing was silently dropped from a list while we were in here.
const counts = {
  "skin tones": skinTones.stored.length,
  hairstyles: hairstyles.stored.length,
  "hair colors": hairColors.stored.length,
  eyewear: eyewear.stored.length,
  expressions: expressions.stored.length,
  "clothing colors": clothingColors.stored.length,
  poses: poses.stored.length,
};
console.log(counts);

const head = await measure("head");
const bust = await measure("bust");
console.log({ head, bust });

await writeFile(
  path.join(
    import.meta.dirname,
    "..",
    "src",
    "lib",
    "art",
    "generated",
    "framing.ts",
  ),
  `// Generated by scripts/measure-framing.ts. Do not edit by hand.
export interface FramingBox {
  x: number;
  y: number;
  width: number;
  height: number;
}

export const framing: Record<'head' | 'bust', FramingBox> = {
  head: ${JSON.stringify(head)},
  bust: ${JSON.stringify(bust)},
};
`,
);
